import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-dental-ppo-underpayment-recovery",
  "engine": "recovery",
  "title": "Dental PPO Underpayment Recovery",
  "shortTitle": "Dental PPO Underpayment Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through dental ppo underpayment recovery",
  "industry": "Dental Revenue Integrity",
  "uiPort": 4603,
  "apiPort": 5603,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Dental PPO Underpayment Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "expectedAmount",
    "actualLabel": "PPO Paid Amount",
    "expectedLabel": "Contract-Expected Amount",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Dental PPO Underpayment Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("ppo-contract-library","DPU01","PPO contract library","Execute ppo contract library using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed ppo contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","PPO contract library Reference","text","DPU01-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("leased-network-mapping","DPU02","Leased-network mapping","Execute leased-network mapping using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed leased-network mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Leased-network mapping Reference","text","DPU02-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("provider-location-registry","DPU03","Provider location registry","Execute provider location registry using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed provider location registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Provider location registry Reference","text","DPU03-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("cdt-procedure-catalog","DPU04","CDT procedure catalog","Execute cdt procedure catalog using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed cdt procedure catalog decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","CDT procedure catalog Reference","text","DPU04-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("claim-eob-ingestion","DPU05","Claim EOB ingestion","Execute claim eob ingestion using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed claim eob ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Claim EOB ingestion Reference","text","DPU05-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("fee-schedule-repricing","DPU06","Fee schedule repricing","Execute fee schedule repricing using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed fee schedule repricing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Fee schedule repricing Reference","text","DPU06-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("alternate-benefit-analysis","DPU07","Alternate benefit analysis","Execute alternate benefit analysis using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed alternate benefit analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Alternate benefit analysis Reference","text","DPU07-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("downgrade-validation","DPU08","Downgrade validation","Execute downgrade validation using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed downgrade validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Downgrade validation Reference","text","DPU08-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("frequency-limitation-review","DPU09","Frequency limitation review","Execute frequency limitation review using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed frequency limitation review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Frequency limitation review Reference","text","DPU09-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("bundling-analysis","DPU10","Bundling analysis","Execute bundling analysis using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed bundling analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Bundling analysis Reference","text","DPU10-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("cob-calculation","DPU11","COB calculation","Execute cob calculation using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed cob calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","COB calculation Reference","text","DPU11-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("missing-payment-detection","DPU12","Missing payment detection","Execute missing payment detection using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed missing payment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Missing payment detection Reference","text","DPU12-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("appeal-generation","DPU13","Appeal generation","Execute appeal generation using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed appeal generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Appeal generation Reference","text","DPU13-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("corrected-claim-submission","DPU14","Corrected claim submission","Execute corrected claim submission using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed corrected claim submission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Corrected claim submission Reference","text","DPU14-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]}),
feature("payer-procedure-analytics","DPU15","Payer procedure analytics","Execute payer procedure analytics using PPO contracts, leased networks, provider locations, CDT procedures, claims, EOBs, fee schedules, alternate benefits, frequency limitations, COB, appeals, and remittances.","Produce a governed payer procedure analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Practice / PPO Claim","text","Practice / PPO Claim · Standard Case"],["caseReference","Payer procedure analytics Reference","text","DPU15-2026-001"],["paidAmount","PPO Paid Amount","currency",642000],["expectedAmount","Contract-Expected Amount","currency",757560],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["PPO contract library case","Leased-network mapping case","Provider location registry case","CDT procedure catalog case","Claim EOB ingestion case"]})
]);
